
// <copyright file="AgentErrorCode.codegen.go" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// <autogenerated />

package discoveryclusterextensioncontract

type AgentErrorCode int

const (
    UnhandledException AgentErrorCode = 950
    NullRefException AgentErrorCode = 951
)

