
// <copyright file="TelemetryEvent.codegen.go" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// <autogenerated />

package discoveryclusterextensioncontract

    type TelemetryEventId int

    const (
        ApplicationStart TelemetryEventId = 2002
        ApplicationStop TelemetryEventId = 2003
)

        func GetApplicationStartEvent(roleName string, version string) TelemetryEvent {
            return getTelemetryEvent (
              ApplicationStart,
              map[string]string {

                    "RoleName": roleName,
                    "Version": version,
            })
        }

        func GetApplicationStopEvent(roleName string, version string, name string) TelemetryEvent {
            return getTelemetryEvent (
              ApplicationStop,
              map[string]string {

                    "RoleName": roleName,
                    "Version": version,
                    "Name": name,
            })
        }

