
// Code generated by controller-gen. DO NOT EDIT.
// <copyright file="AgentErrorCode.go" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// <autogenerated />

package discoveryextensionevents

type AgentErrorCode int

const (
    UnhandledException AgentErrorCode = 950
    NullRefException AgentErrorCode = 951
)

